config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flights, only: [:index, :show] do
    resources :bookings, only: [:new, :create] 
  end
  
  resources :bookings, only: [:show]
  root 'flights#index'
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :flights
  has_many :departing_flights, foreign_key: :start_id, class_name: 'Flight'
  has_many :arriving_flights, foreign_key: :finish_id, class_name: 'Flight'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :bookings_passengers
  has_many :passengers, through: :bookings_passengers
  accepts_nested_attributes_for :bookings_passengers
end

app/models/bookings_passenger.rb
class BookingsPassenger < ApplicationRecord
  belongs_to :booking
  belongs_to :passenger
  accepts_nested_attributes_for :passenger
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, foreign_key: :start_id, class_name: 'Airport'
  belongs_to :to_airport, foreign_key: :finish_id, class_name: 'Airport'
  has_many :bookings
  has_many :passengers, through: :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :bookings_passengers
  has_many :bookings, through: :bookings_passengers
  has_many :flights, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @flight = Flight.find(params[:flight_id])
    @booking.flight = @flight
    passenger_count = params[:passenger_count].to_i

    passenger_count.times do 
      @booking.bookings_passengers.build.build_passenger
    end
  end

  def create
    @booking = Booking.new(booking_params)
    @flight = Flight.find(params[:flight_id])
    @booking.flight = @flight
    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: "Your flight has been booked!"}
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unproccessable_entity }
      end
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, bookings_passengers_attributes: [passenger_attributes: [:name, :email]])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    @airports = Airport.all
    @dates = Flight.pluck(:start_date).uniq
    @search = params
    @passenger_count = params[:passenger_count]
    
    if @search.present?
      @flights = Flight.where(start_id: @search[:from_airport], 
                              finish_id: @search[:to_airport], 
                              start_date: @search[:start_date])
    end
  end

  private

  # def flights_params
  #   params.require(:flight).permit(:airport)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<section class="section">
    <div class="columns is-justify-content-center is-mobile is-vcentered">
        <div class="column is-8">
            <h1 class="title mb-6">Book this flight!</h1>        
        
            <h2 class="subtitle has-text-weight-semibold mb-2"> 
                <%= @flight.from_airport.name %> to <%= @flight.to_airport.name %> 
            </h2>
            <p class="has-text-weight-medium"><%= @flight.start_date.strftime('%a, %b %d')%></p>


            <%= simple_form_for @booking, url: flight_bookings_url, html: { class: "mt-6" } do |f| %>
                <%= f.error_notification %>

                <h2 class="subtitle">Enter Passenger Information: </h2>
                
                <% if @booking.errors.any? %>
                    <div id="error_explanation">
                        <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
                        <ul>
                        <% @booking.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                        </ul>
                    </div>
                <% end %>

                <%= f.simple_fields_for :bookings_passengers do |bp_form| %>
                    <%= bp_form.simple_fields_for :passenger do |p_form| %>

                        <div id="passenger-forms" class="block">
                            <div class="field">
                                <div class="control">
                                    <%= p_form.input :name, wrapper: false, required: true, label_html: { class: "label" }, input_html: { class: "input" } %>
                                </div>
                            </div>

                            <div class="field">
                                <div class="control">
                                    <%= p_form.input :email, wrapper: false, required: true, label_html: { class: "label" }, input_html: { class: "input" } %>
                                </div>
                            </div>
                        </div>


                    <% end %>
                <% end %>

                <%= f.submit 'Create Booking' %>
            <% end %>

        </div>
    </div>
</section>

app/views/bookings/show.html.erb
<section class="section">
    <div class="columns is-justify-content-center is-mobile is-vcentered">
        <div class="column is-8">
            <h1 class="title mb-6">Your Flight</h1>        
        
            <h2 class="subtitle has-text-weight-semibold mb-2"> 
                <%= @booking.flight.from_airport.name %> to <%= @booking.flight.to_airport.name %> 
            </h2>
            <p class="has-text-weight-medium"><%= @booking.flight.start_date.strftime('%a, %b %d')%></p>



            <div class="container mt-6">
                <h2 class="subtitle has-text-weight-semibold">Passengers:</h2>
                <% @booking.passengers.each do |passenger| %>
                    <p class="has-text-weight-medium">- <%= passenger.name %> </p>
                <% end %>
                
            </div>

        </div>
    </div>
</section>

app/views/flights/index.html.erb
<section id="main-hero" class="hero is-halfheight is-flex is-justify-content-center mb-3">
    <div class="columns is-vcentered is-justify-content-center is-mobile">
        <div class="column is-8">
            <div class="card is-flex is-justify-content-center p-2">
                <div class="card-content">
                    <%= form_with url: root_path, method: :get, html: { class: "is-flex is-justify-content-center is-align-items-center is-flex-direction-column" } do |f| %>

                        <div class="field is-grouped is-grouped-multiline">
                            <div class="control ">
                                <div class="select ">
                                    <%= f.collection_select :from_airport, @airports, :id, :name, prompt: 'From' %>
                                </div>
                            </div>

                            <div class="control">
                                <div class="select">
                                    <%= f.collection_select :to_airport, @airports, :id, :name, prompt: 'To' %>
                                </div>
                            </div>

                            <div class="control">
                                <div class="select">
                                    <%= f.select :start_date, @dates.collect{ |date| [date.strftime('%a, %b %d'), date] }, prompt: 'Start date' %> 
                                </div>
                            </div>

                            <div class="control">
                                <div class="select">
                                <%= f.select :passenger_count, 1..4, prompt: 'Passengers'  %>
                                </div>
                            </div>
                        </div>

                        <%= f.submit 'Search', class: "button is-primary is-rounded " %>
                    <% end %>
                </div>
                
            </div>
        </div>
    </div>
</section>


<section id="flights" class="section">
        <div class="columns is-justify-content-center is-mobile">
            <div class="column is-8 ">
            <% if @flights.present? %> 
                <% @flights.each do |flight|%>  

                    <div class="block p-4 border">
                        <%= form_with url: new_flight_booking_path(flight), method: :get do |f| %> 
                            <%= f.hidden_field :passenger_count, value: @passenger_count %>

                            <div class="level">
                                <div class="level-item">
                                    <span> 
                                        <%= flight.from_airport.airport_code %> - <%= flight.to_airport.airport_code %> 
                                    </span>
                                </div>

                                <div class="level-item">
                                    <span><%= flight.start_date.strftime('%a, %b %d')%></span>
                                </div>

                                <div class="level-item">
                                    <%= f.submit 'Select', class: "button is-primary is-small" %>
                                </div>
                            </div>
                        <% end %>

                    </div>
                <% end %>
            <% end %>

            </div>
        </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Runaway</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="columns is-mobile is-justify-content-center mb-0 has-border-bottom">
      <div class="column is-8">

        <nav class="navbar is-white ">
          <div class="navbar-brand">
            <%= link_to root_path, class: "navbar-item" do %>
              <span class="icon-text">
                <span class="icon">
                  <i class="las la-plane la-2x mr-1"></i>
                </span>
                <span class="title is-size-3"> Runaway </span>
              </span>
            <% end %>
          </div>
        </nav>

      </div>
    </div>
    <%= yield %>
  </body>
</html>